
name: TEST & TYPE-CHECK

on: 
  pull_request:
              branches: 
                      - dev
jobs:
     builds:
            runs-on: ubuntu-latest
            steps: 
                  - uses: actions/checkout@v3
                    with: 
                      fetch-depth: 0
                  - name: Install dependencies
                    run: npm i
                  - name: TYPE-CHECK
                    run: npm run type-check  
                  - name: Test packages
                    run: npm run test:unit
                